version: '3.8'
services:
  app:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    container_name: hate_classifier
    volumes:
      - ./src:/app
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:latest
    container_name: mongo_social
    ports:
      - "27017:27017"